"""empty message

Revision ID: bd8bbacd259f
Revises: d8c4fb853289
Create Date: 2021-08-25 11:30:36.767162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8bbacd259f'
down_revision = 'd8c4fb853289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('showname', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'showname')
    # ### end Alembic commands ###
